# All details about hydra configuration available here:
# [https://hydra.cc]
run:
    dir: ${work_dir}/runs/${now:%Y-%m-%d_%H-%M-%S}
sweep:
    dir: ${work_dir}/multiruns/${now:%Y-%m-%d_%H-%M-%S}_${hydra.sweeper.sampler.seed}
    subdir: ${hydra.job.num}

# You can set here environment variables that are universal for all users.
# For system specific variables (like data paths) it's better to use .env file!
job:
  env_set:
    EXAMPLE_VAR: "example_value"
