# LightGBM parameters available here:
# [https://lightgbm.readthedocs.io/en/latest/Parameters.html]
name: lightgbm
objective: regression
boosting: gbdt
learning_rate: 0.008355030218065131
num_leaves: 47
device: cpu
max_depth: -1
min_data_in_leaf: 2
feature_fraction: 0.6481092835614777
bagging_fraction: 0.7681119659704174
bagging_freq: 5
verbose: -1
metric: l1
max_epochs: ${max_epochs}
patience: ${patience}
