# Parameters for pytorch_tabular models available here:
# [https://github.com/manujosephv/pytorch_tabular/tree/main/pytorch_tabular/models]
name: pytorch_tabular_tab_transformer
_target_: src.models.tabular.pytorch_tabular.tab_transformer.PTTabTransformerModel
task: regression
loss_type: "L1Loss"
input_dim: ${in_dim}
output_dim: ${out_dim}
optimizer_lr: 0.01
optimizer_weight_decay: 0.0
scheduler_step_size: 100
scheduler_gamma: 0.8
embedding_dims: null
categorical_cardinality: null
continuous_cols: null
categorical_cols: null
input_embed_dim: 32
embedding_dropout: 0.1
share_embedding: False
share_embedding_strategy: "fraction"
shared_embedding_fraction: 0.25
num_heads: 8
num_attn_blocks: 6
transformer_head_dim: null
attn_dropout: 0.1
add_norm_dropout: 0.1
ff_dropout: 0.1
ff_hidden_multiplier: 4
transformer_activation: "GEGLU"
out_ff_layers: "128-64-32"
out_ff_activation: "ReLU"
out_ff_dropout: 0.0
use_batch_norm: False
batch_norm_continuous_input: False
out_ff_initialization: "kaiming"
