# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "mean_absolute_error"
optimized_mean: "cv_mean" # "cv_mean_val_tst"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: null

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: minimize

    # total number of runs that will be executed
    n_trials: 1000

    # choose Optuna hyperparameter sampler
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.TPESampler
      seed: ${seed}
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 128
      n_ei_candidates: 16
      multivariate: false
      warn_independent_sampling: true

    # define range of hyperparameters
    params:
      danet.optimizer_lr: tag(log, interval(0.00001, 1)) # tag(log, interval(0.00001, 1))
      danet.optimizer_weight_decay: tag(log, interval(0.0000001, 0.1)) # tag(log, interval(0.00000001, 0.1))
      danet.layer_num: int(range(4, 40, step=1)) # int(range(8, 32, step=1))
      danet.base_outdim: choice(16, 32, 64, 96, 128) #  choice(32, 64, 96)
      danet.k: choice(3, 4, 5, 6, 7) # choice(4, 5, 6)
      danet.drop_rate: interval(0.0, 0.2) # choice(0.0, 0.1)
