_target_: src.datamodules.tabular.TabularDataModule
task: "classification"
feats_con_fn: "${base_dir}/feats_con.xlsx"
feats_cat_fn: null
feats_labels_col: null
feats_cat_replace_col: null
feats_cat_encoding: label
feats_cat_keep: True
feats_cat_embed_dim: ${embed_dim}
target: ${target}
target_label: ${target_label}
target_classes_fn: "${data_dir}/statuses.xlsx"
data_fn: "${data_dir}/data.xlsx"
data_index: index
data_imputation: fast_knn
split_by: trn_val
split_trn_val: [0.80, 0.20]
split_top_feat: null
split_explicit_feat: Split
batch_size: 16384
num_workers: 0
pin_memory: False
seed: ${seed}
weighted_sampler: True
