# LightGBM parameters available here:
# [https://lightgbm.readthedocs.io/en/latest/Parameters.html]
name: lightgbm
output_dim: ${out_dim}
objective: multiclass
boosting: gbdt
learning_rate: 0.01
num_leaves: 20
device: cpu
max_depth: -1
min_data_in_leaf: 10
feature_fraction: 0.8
bagging_fraction: 0.8
bagging_freq: 5
verbose: -1
metric: multi_logloss
max_epochs: ${max_epochs}
patience: ${patience}
