name: nbm_spam_nam
_target_: src.models.tabular.nbm_spam.nam.NAMModel
task: regression
loss_type: "L1Loss"
input_dim: ${in_dim}
output_dim: ${out_dim}
optimizer_lr: 0.001
optimizer_weight_decay: 0.0
scheduler_step_size: 100
scheduler_gamma: 0.8
nary: null
first_layer: "linear"
first_hidden_dim: 64
hidden_dims: [64, 32]
num_subnets: 1
dropout: 0.0
concept_dropout: 0.0
batchnorm: True
output_penalty: 0.0
polynomial: null
