# LightGBM parameters available here:
# [https://lightgbm.readthedocs.io/en/latest/Parameters.html]
name: lightgbm
objective: regression
boosting: gbdt
learning_rate: 0.07041009772065657
num_leaves: 73
device: cpu
max_depth: -1
min_data_in_leaf: 3
feature_fraction: 0.779551909739833
bagging_fraction: 0.6106882775965441
bagging_freq: 5
verbose: -1
metric: l1
max_epochs: ${max_epochs}
patience: ${patience}
