# XGBoost parameters available here:
# [https://xgboost.readthedocs.io/en/stable/parameter.html]
name: xgboost
output_dim: ${out_dim}
booster: 'gbtree'
learning_rate: 0.05
max_depth: 5
gamma: 0
sampling_method: 'uniform'
subsample: 1
objective: 'multi:softprob'
verbosity: 0
eval_metric: 'mlogloss'
max_epochs: ${max_epochs}
patience: ${patience}
